apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "projects.example.mydev.org"
spec:
  group: "example.mydev.org"
  versions:
    - name: "v1alpha1"
      served: true
      storage: true
  scope: "Namespaced"
  names:
    plural: "projects"
    singular: "project"
    kind: "Project"
    shortNames:
      - "proj"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicas"]
          properties:
            replicas:
              type: "integer"
              minimum: 1